#testing TRAVIS CI (in MercuriatScrapbook)
language: python
python:
  - "3.7"
  - "nightly"
install:
  - "pip install pytest"
  - "pip install -r video_code/requirements.txt"
script: python -m pytest tests/